-- 1. 테이블 생성
CREATE TABLE JOB(
    JOB_CODE CHAR(2) NOT NULL,
    JOB_NAME VARCHAR2(35)
);

-- 2. 커멘트 추가
COMMENT ON COLUMN JOB.JOB_CODE IS '직급코드';
COMMENT ON COLUMN JOB.JOB_NAME IS '직급명';

--3. 데이터 추가
INSERT INTO JOB(JOB_CODE, JOB_NAME)
VALUES('J1', '대표');

INSERT INTO JOB(JOB_CODE, JOB_NAME)
VALUES ('J2', '부사장');

INSERT INTO JOB(JOB_CODE, JOB_NAME)
VALUES ('J3', '부장');

INSERT INTO JOB(JOB_CODE, JOB_NAME)
VALUES('J4', '차장');

INSERT INTO JOB(JOB_CODE, JOB_NAME)
VALUES('J5', '과장');

INSERT INTO JOB(JOB_CODE, JOB_NAME)
VALUES('J6', '대리');

INSERT INTO JOB(JOB_CODE, JOB_NAME)
VALUES('J7', '사원');

SELECT * FROM JOB;