-- 1. 테이블 생성
CREATE TABLE LOCATION(
    LOCAL_CODE CHAR(2) NOT NULL,
    NATIONAL_CODE CHAR(2) NOT NULL,
    LOCAL_NAME VARCHAR2(40)
);

-- 2. 코멘트 추가
COMMENT ON COLUMN LOCATION.LOCAL_CODE IS '지역코드';
COMMENT ON COLUMN LOCATION.NATIONAL_CODE IS '국가코드';
COMMENT ON COLUMN LOCATION.LOCAL_NAME IS '지역명';

-- 3. 데이터 추가
INSERT INTO LOCATION(LOCAL_CODE, NATIONAL_CODE, LOCAL_NAME)
VALUES('L1', 'KO', 'ASIA1');

INSERT INTO LOCATION(LOCAL_CODE, NATIONAL_CODE, LOCAL_NAME)
VALUES('L2', 'JP', 'ASIA2');

INSERT INTO LOCATION(LOCAL_CODE, NATIONAL_CODE, LOCAL_NAME)
VALUES('L3', 'CH', 'ASIA3');

INSERT INTO LOCATION(LOCAL_CODE, NATIONAL_CODE, LOCAL_NAME)
VALUES('L4', 'US', 'AMERICA');

INSERT INTO LOCATION(LOCAL_CODE, NATIONAL_CODE, LOCAL_NAME)
VALUES('L5', 'RU', 'EU');

SELECT * FROM LOCATION;
