-- 1. 테이블 생성

CREATE TABLE NATIONAL(
    NATIONAL_CODE CHAR(2) NOT NULL,
    NATIONAL_NAME VARCHAR2(35)
);

-- 2. 코멘트 생성
COMMENT ON COLUMN NATIONAL.NATIONAL_CODE IS '국가코드';
COMMENT ON COLUMN NATIONAL.NATIONAL_NAME IS '국가명';

-- 3. 데이터 추가
INSERT INTO NATIONAL(NATIONAL_CODE, NATIONAL_NAME)
VALUES('KO', '한국');

INSERT INTO NATIONAL(NATIONAL_CODE, NATIONAL_NAME)
VALUES('JP', '일본');

INSERT INTO NATIONAL(NATIONAL_CODE, NATIONAL_NAME)
VALUES('CH', '중국');

INSERT INTO NATIONAL(NATIONAL_CODE, NATIONAL_NAME)
VALUES('US', '미국');

INSERT INTO NATIONAL(NATIONAL_CODE, NATIONAL_NAME)
VALUES('RU', '러시아');

-- 출력
SELECT * FROM NATIONAL;