-- 1. 테이블 생성
CREATE TABLE SAL_GRADE(
    SAL_LEVEL CHAR(2) NOT NULL,
    MIN_SAL NUMBER,
    MAX_SAL NUMBER
);

-- 2. 코멘트 추가
COMMENT ON COLUMN SAL_GRADE.SAL_LEVEL IS '급여등급';
COMMENT ON COLUMN SAL_GRADE.MIN_SAL IS '최소급여';
COMMENT ON COLUMN SAL_GRADE.MAX_SAL IS '최대급여';

-- 3. 데이터 추가
INSERT INTO SAL_GRADE(SAL_LEVEL, MIN_SAL, MAX_SAL)
VALUES('S1', 60000, 100000);

INSERT INTO SAL_GRADE(SAL_LEVEL, MIN_SAL, MAX_SAL)
VALUES('S2', 50000, 599999);

INSERT INTO SAL_GRADE(SAL_LEVEL, MIN_SAL, MAX_SAL)
VALUES('S3', 40000, 499999);

INSERT INTO SAL_GRADE(SAL_LEVEL, MIN_SAL, MAX_SAL)
VALUES('S4', 30000, 399999);

INSERT INTO SAL_GRADE(SAL_LEVEL, MIN_SAL, MAX_SAL)
VALUES('S5', 20000, 299999);

INSERT INTO SAL_GRADE(SAL_LEVEL, MIN_SAL, MAX_SAL)
VALUES('S6', 10000, 199999);

-- 출력
SELECT * FROM SAL_GRADE;
